########################################################
### EMBEDDED SERVER CONFIGURATION (ServerProperties) ###
########################################################
server:
  port: 8091
  session:
    timeout: 28800

##############
### SPRING ###
##############
spring:
  application:
    name: micro-service-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                                                 # 指定数据源
    initialize: false
    schema: classpath:schema.sql                              # 指定数据库的建表脚本
    data: classpath:data.sql                                  # 指定数据库的数据脚本
    url: jdbc:mariadb://192.168.1.138:3306/mifan_user_center?useUnicode=true&autoReconnect=true
    username: root
    password: budee123
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      max-active: 100
      max-wait: 60000
      max-idle: 8
      min-idle: 1
      initial-size: 10
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 30000
  redis:
    host: 192.168.1.138
    port: 6379
  output:
    ansi:
      enabled: always

###########################
### SECURITY PROPERTIES ###
###########################
security:
  basic:
    enabled: false
  user:
    name: user
    password: user

###############
### LOGGING ###
###############
logging:
  level:
    root: INFO
    org.hibernate: INFO                                       # 配置日志级别，让hibernate打印出执行的SQL
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.commons.util.InetUtils: TRACE   # 开启这边的日志，可以打印出Spring查找网卡的过程

##############
### EUREKA ###
##############
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://mifan:Mifan2017!@localhost:8761/eureka/

########################
### APPLICATION CORE ###
########################
moon:
  data:
    token:
      token-header: Authorization
      token-head: Bearer
      secret: budee123
      expiration: 7200
      remember-me-expiration: 604800
      salt: f817fcf6-f6af-4c95-89fe-637838078bc9
      redirect: http://www.mifanxing.com/
    wxpay:
      mchID: 1488379182
      notifyUrl: https://api.mch.weixin.qq.com/mmpaymkttransfers/sendredpack
      key: mifanxingsongningbo1234588888888
      sendName: 米饭星
      wishing: 想了解更多音频知识，请关注・米饭星・~~
      clientIp: 121.42.161.53
      actName: 米饭星・注册送红包
      remark: 没有备注
      totalNum: 1
      certPath: D://cert/apiclient_cert.p12
      redirect: http://www.mifanxing.com/Wregisterresult/
  security:
    cas:
      filter:
        appKey: d1b914ef-2908-45db-adf2-dd8ceffe61af
  model:
    mybatis:
      config-location: com/mifan/user/mybatis-config.xml
  web:
    micro-service:
      enabled: true

##########################
### APPLICATION CONFIG ###
##########################
mifan:
  proxy:
    isUse: false
    server: 192.168.1.138
    port: 3128