########################################################
### EMBEDDED SERVER CONFIGURATION (ServerProperties) ###
########################################################
server:
  port: 8090
  session:
    timeout: 28800

##############
### SPRING ###
##############
spring:
  aop:
    auto: true                                          # Add @EnableAspectJAutoProxy.
    proxy-target-class: false                           # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
 # jpa:
 #   generate-ddl: false
 #   show-sql: false
 #   hibernate:
 #     ddl-auto: none
  redis:
    database: 0
    host: 192.168.1.138
    port: 6379
  data:
    mongodb:
      host: 192.168.1.138
      port: 27017
      database: award
      username: '{cipher}545b3995ddd39d4058b1feb8dd160f995ed2dcc1a9156392778768965573e869'
      password: '{cipher}696c1b124b662fc0e950e3416627bcbf80b457163991474f6605eea497ad544d'
      repositories:
        enabled: true
  rabbitmq:
    host: 192.168.1.138
    port: 5672
    username: '{cipher}08d2ffd2c64fd5af8ed42cae05f9427402add6c7cfdd82395b9713589128a728'
    password: '{cipher}08d2ffd2c64fd5af8ed42cae05f9427402add6c7cfdd82395b9713589128a728'
  output:
    ansi:
      enabled: always

###########################
### SECURITY PROPERTIES ###
###########################
security:
  basic:
    enabled: false
  user:
    name: '{cipher}7a696f2784598274526281a46c2ad71664d74fe4480108059b8402349e27031d'
    password: '{cipher}7a696f2784598274526281a46c2ad71664d74fe4480108059b8402349e27031d'

###############
### LOGGING ###
###############
logging:
  level:
    root: INFO
    org.hibernate: INFO                                       # 配置日志级别，让hibernate打印出执行的SQL
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.springframework.cloud.commons.util.InetUtils: INFO    # 开启这边的日志，可以打印出Spring查找网卡的过程

#############
### FEIGN ###
#############
feign:
  httpclient:
    connection-timeout: 10000
  hystrix:
    enabled: true

############################# To set thread isolation to SEMAPHORE,
### FEIGN HYSTRIX SUPPORT ### RequestContextHolder.getRequestAttributes() read from Thread Local, so need to set hystrix isolation strategy to SEMAPHORE
#############################
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
    micro-service-user:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
  SocketTimeout: 60000

########################
### Application Core ###
########################

##########################
### APPLICATION CONFIG ###
##########################
application:
  idworker:
    workerId: 2
    datacenterId: 2
  scheduler:
    enable:
      prize: false