##############
### EUREKA ###
##############
# eureka.client.healthcheck.enabled=true should only be set in application.yml. Setting the value in bootstrap.yml will cause undesirable side effects like registering in eureka with an UNKNOWN status.
eureka:
  client:
    healthcheck:
      enabled: true                             # 开启健康检查
  instance:
    lease-expiration-duration-in-seconds: 30    # 续约到期时间
    lease-renewal-interval-in-seconds: 10       # 续约更新时间间隔

##############
### Zipkin ###
##############
# If using Zipkin, configure the percentage of spans exported using spring.sleuth.sampler.percentage (default 0.1, i.e. 10%). Otherwise you might think that Sleuth is not working cause it’s omitting some spans.
# Percentage of requests that should be sampled. E.g. 1.0 - 100% requests should be sampled. The precision is whole-numbers only (i.e. there’s no support for 0.1% of the traces).
spring:
  sleuth:
    sampler:
      percentage: 1.0

########################################################
### EMBEDDED SERVER CONFIGURATION (ServerProperties) ###
########################################################
server:
  port: 9092

##############
### SPRING ###
##############
spring:
  datasource:                                                 # 指定数据源
    url: jdbc:mariadb://192.168.1.138:3306/mifan_reward?useUnicode=true&autoReconnect=true
  rabbitmq:
    host: 192.168.1.138
    port: 5672
    username: '{cipher}c473d35322c2826fe0cd5f169d3a2e7b656b2f8940830ed2e4bdc694bc9b5324'
    password: '{cipher}c473d35322c2826fe0cd5f169d3a2e7b656b2f8940830ed2e4bdc694bc9b5324'
  redis:
    database: 0
    host: 192.168.1.138
    port: 6379

##########################
### APPLICATION CONFIG ###
##########################
application:
  idworker:
    workerId: 4
    datacenterId: 4
  scheduler:
    enable:
      prize: false
mifan:
  proxy:
    isUse: false
    server: 192.168.1.229
    port: 3128